spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./data/uniparts-dev;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

logging:
  level:
    com.example.parts: DEBUG
